### ISSUE TITLE
Add test and fix "undefined" for scope not set

### ISSUE THREAD

**Issue by bahmutov** [350-mass-cambridge-somerville/350-actions-client#13]
<img width="702" alt="Screen Shot 2020-02-11 at 12 44 58 PM" src="https://user-images.githubusercontent.com/2212006/74263279-7ea4f280-4ccc-11ea-8f9a-4a34133eef00.png">

**Comment by bahmutov** [comment]
In past action card 24

<img width="714" alt="Screen Shot 2020-03-11 at 5 43 15 PM" src="https://user-images.githubusercontent.com/2212006/76467359-d6b04100-63bf-11ea-9c56-f4083a73f883.png">

**Comment by ccpowers** [comment]
@bahmutov I agree...

**Comment by bahmutov** [comment]
I think once we get over DNS and deploys are automatic after the tests pass, it will be smooth sailing in fixing issues and updating features
