### ISSUE TITLE
The current card says Feb 17th?

### ISSUE THREAD

**Issue by bahmutov** [350-mass-cambridge-somerville/350-actions-client#15]
@ccpowers is the current card (served by Netlify, huzza) says Feb 17th - is this correct?

<img width="903" alt="Screen Shot 2020-03-07 at 1 59 33 PM" src="https://user-images.githubusercontent.com/2212006/76150764-fe2fa280-607b-11ea-88c5-1fb172f2b8aa.png">

**Comment by bahmutov** [comment]
I see the new card now, all good

**Comment by ccpowers** [comment]
@bahmutov Yeah sorry! I was just really delayed in posting it. Next priority is finding a way for other people to be able to upload the cards so it's not reliant on me doing it.
