### ISSUE TITLE
find free hosting solution

### ISSUE THREAD

**Issue by ccpowers** [350-mass-cambridge-somerville/350-actions-client#3]
@bahmutov - repo is now public and owned by `350-mass-cambridge-somerville` organization. We need find a free hosting + deployment solution.

**Comment by bahmutov** [comment]
Perfect, I am trying to connect Netlify to this repo - you should have gotten a request @ccpowers, could you approve it, please?

**Comment by ccpowers** [comment]
@bahmutov request approved! Are you planning to do it via github actions? Just curious

**Comment by bahmutov** [comment]
Yes, there are already GitHub actions running to run tests and reformat code if needed

**Comment by ccpowers** [comment]
@bahmutov I've added tests in the `feat/katy-master` branch for the past action view and updated it to master, I think if we can merge that it'll be ready to host
