### ISSUE TITLE
is the current action card view broken?

### ISSUE THREAD

**Issue by bahmutov** [350-mass-cambridge-somerville/350-actions-client#4]
The backend is returning the correct current action, yet the current action card view is broken

<img width="921" alt="Screen Shot 2020-02-03 at 9 59 13 PM" src="https://user-images.githubusercontent.com/2212006/73709902-6d5a5580-46d0-11ea-980d-37bab261b0b2.png">

I think this commit https://github.com/350-mass-cambridge-somerville/350-actions-client/commit/6e18b239c62ff57dbc6c6644c22b350f5be81ec3#diff-a131685338a9b65224781db86d8b3886 seems to be the culprit

It used to have 
```
<CurrentActionDisplay actionCard={this.state.actionCard}  
onChange={this.onChange} userData={this.context.userData}/>);
```

and now it has just name form

**Comment by ccpowers** [comment]
@bahmutov yes, you are correct. I just realized I had some work on my "master" branch locally which was refactoring the current action view, and origin/master is out of date. Your fix in the e2e pr is fine for now.

**Comment by bahmutov** [comment]
super, closing this for now
