### ISSUE TITLE
card needs white backround

### ISSUE THREAD

**Issue by bahmutov** [350-mass-cambridge-somerville/350-actions-client#8]
how do we get background colors into the theme?

<img width="1440" alt="Screen Shot 2020-02-05 at 9 31 36 PM" src="https://user-images.githubusercontent.com/2212006/73900833-f7382900-485e-11ea-9be6-c6c613ea79b0.png">

The original looks nice

<img width="1440" alt="Screen Shot 2020-02-05 at 9 32 25 PM" src="https://user-images.githubusercontent.com/2212006/73900865-06b77200-485f-11ea-9f5e-13dfbbca7c25.png">

**Comment by ccpowers** [comment]
Hey @bahmutov - if you use the branch `feat/katy-master` (now updated with cypress test), the white background will show up. If that doesn't work i'll track it down.
