### ISSUE TITLE
How does the "past" work?

### ISSUE THREAD

**Issue by bahmutov** [350-mass-cambridge-somerville/350-actions-client#9]
I cannot see any requests coming from the application when I click "past", and I would love to recreate the functionality from http://maclimateactions.com/past

**Comment by ccpowers** [comment]
It should be fetching all action cards, see `PastActionView.tsx` line 14. It happens in the `componentDidMount` function, so you'll need to refresh to see the request to the actioncards/ url. The branch that is deployed is what is on `feat/katy-master` so I would look at that (I was using a different back end before, and so the data structure changed and I no longer need to fetch actions and survey responses separately).
If that doesn't help, let me know what steps you are using to look at the requests and I will follow them as well.
